services:
  chart-show:
    image: ghcr.io/rarneson/the-current-chart-show-sync:latest
    container_name: chart-show
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    volumes:
      - ./.env:/app/.env
